-- Insert sample historical tickets with resolutions
INSERT INTO tickets (customer_email, customer_name, subject, description, category, priority, status, agent_response, resolved_at) VALUES
('john@example.com', 'John Smith', 'Order not delivered', 'I ordered a laptop 2 weeks ago but it hasnt arrived yet. The tracking shows it was shipped but no updates since then.', 'shipping', 'high', 'resolved', 'I apologize for the delay. I have contacted our shipping partner and your package was delayed due to weather. It will be delivered tomorrow. As compensation, we are providing a $20 credit to your account.', NOW() - INTERVAL '2 days'),

('sarah@example.com', 'Sarah Johnson', 'Want to return shoes', 'The shoes I ordered are too small. I need to return them and get a refund.', 'returns', 'medium', 'resolved', 'I can help you with the return. Since the shoes are within our 30-day return window, I am sending you a prepaid return label. Once we receive the shoes, your refund will be processed within 5-7 business days.', NOW() - INTERVAL '5 days'),

('mike@example.com', 'Mike Wilson', 'Payment charged twice', 'My credit card was charged twice for the same order but I only received one confirmation email.', 'payment', 'high', 'resolved', 'I see the duplicate charge on your account. This was a processing error on our end. I have initiated a refund for the duplicate charge which will appear on your statement within 3-5 business days. You will receive a confirmation email shortly.', NOW() - INTERVAL '1 day'),

('lisa@example.com', 'Lisa Brown', 'Damaged product received', 'The phone case I ordered arrived cracked. The packaging was also damaged.', 'quality', 'medium', 'resolved', 'I am sorry about the damaged phone case. I am sending you a replacement immediately with expedited shipping at no charge. Please keep the damaged item - no need to return it. You should receive the replacement within 2 business days.', NOW() - INTERVAL '3 days'),

('david@example.com', 'David Lee', 'Cannot access my account', 'I forgot my password and the reset email is not coming through.', 'account', 'low', 'resolved', 'I can help you regain access to your account. I have manually sent a password reset link to your email. Please check your spam folder as well. If you still do not receive it, please let me know and I can reset your password directly.', NOW() - INTERVAL '1 week');
